[package]
name = "rust-sokoban"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.7"
glam = { version = "0.20.0", features = ["mint"]}
specs = { version = "0.17.0", features = ["specs-derive"]}
